# Generated by Django 5.1.4 on 2024-12-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('cin', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('post', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin_artist', 'Admin Artist'), ('admin_user', 'Admin User'), ('admin_galery', 'Admin Galery'), ('admin_paiment', 'Admin Paiment')], max_length=20)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
